# Generated by Django 4.2.3 on 2023-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenurl',
            field=models.CharField(max_length=100000),
        ),
    ]
