# Generated by Django 4.2.3 on 2023-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioactual',
            field=models.IntegerField(default='0'),
        ),
    ]
