# Generated by Django 4.2.3 on 2023-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_producto_precioactual'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='comprador_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='oferta',
            name='oferta',
            field=models.IntegerField(default=False),
        ),
    ]
