# Generated by Django 4.2.3 on 2023-07-10 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_producto_precioactual'),
        ('auctions', '0007_oferta_comprador_id_oferta_oferta'),
    ]

    operations = [
    ]
