# Generated by Django 4.2.3 on 2023-07-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_merge_20230710_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.IntegerField()),
                ('comentador_id', models.IntegerField()),
                ('comentario', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioactual',
            field=models.IntegerField(default=0),
        ),
    ]
