# Generated by Django 4.2.3 on 2023-07-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comentario_alter_producto_precioactual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentador_id',
            new_name='comentario_id_usuario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='producto_id',
            new_name='comentario_producto_id',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=100000),
        ),
    ]
