# Generated by Django 4.2.3 on 2023-07-13 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_seguimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='seguido',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='seguimiento_id_producto',
        ),
        migrations.RemoveField(
            model_name='seguimiento',
            name='seguimiento_id_usuario',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='productos',
            field=models.ManyToManyField(to='auctions.producto'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
