# Generated by Django 4.2.3 on 2023-07-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listaseguimiento_delete_seguimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario_id_usuario',
            new_name='comentador_id',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario_producto_id',
            new_name='producto_id',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='ListaSeguimiento',
        ),
    ]
