# Generated by Django 4.2.3 on 2023-07-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_seguimiento_en_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.producto'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.producto'),
        ),
    ]
