# Generated by Django 4.2.3 on 2023-07-15 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_seguimiento_en_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.producto')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
